version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

parameters:
  runloadtests:
    type: boolean
    default: false
  CIRCLE_TAG:
    type: string
    default: ""
  working-pachyderm-version:
    type: string
    default: "v2.4.0"
  run_nightly_tag:
    type: boolean
    default: false

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout # checkout code
      #- run: # run a command
      #    name: Generate config
      #    command: |
      - continuation/continue:
          configuration_path: .circleci/main.yml # use newly generated config to continue
  create-nightly-tag:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          name: create nightly tag
          command: |
            TIMESTAMP=$(date +'%Y%m%d')
            WORKINGVERSION=<< pipeline.parameters.working-pachyderm-version >>
            NIGHTLY=${WORKINGVERSION}-nightly.${TIMESTAMP}
            git tag -am "nightly release tag ${NIGHTLY}" ${NIGHTLY}
            git push origin ${NIGHTLY}

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    when:
      and:
        - not: << pipeline.parameters.run_nightly_tag >>
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
  create-nightly-tag:
    when: << pipeline.parameters.run_nightly_tag >>
    jobs:
      - create-nightly-tag
